### ISSUE TITLE
Crash Sound.XUsoundTitleGenerators

### ISSUE THREAD

**Issue by ghost** [rwtema/extrautilities_old_issues#230] opened 2014-08-10 15:49 UTC
Sometimes I crash and get this error:
http://pastebin.com/ZJVKaUSm

**Comment by MrWrecks** [comment] 2014-08-11 00:47
I'm having the same problem. Game crashes every time after about 5 seconds.

http://pastebin.com/2wzn496s

**Comment by rwtema** [comment] 2014-08-11 08:54
Dupe of #205

**Closed as completed by rwtema** 2014-08-11 08:54 UTC
