### ISSUE TITLE
1.9.4 Duping Bug with Transfer nodes + crash (Fixed)

### ISSUE THREAD

**Issue by Severance213** [rwtema/extrautilities_old_issues#892] opened 2016-06-18 11:31 UTC
When ever I break a transfer node with a TCon pick axe I get two back. Then when I tried to use Extra Utils miner to break the node I crashed with this log. 
http://pastebin.com/iyzqgRDw

**Comment by ghost** [comment] 2016-07-02 12:18
I can also confirm that this is indeed true and its not isolated to just tinkers tools i have reproduced this using multiple mods such as the drill from Actually Addons and normal vanilla Picks. When broken it gives back two each time. 

Version of Extra Utils : extrautils2-1.9.4-alpha-1.0.0a
Running the Avant 2 Modpack, 

The only thing that does not occur is the server does not crash nor does the client.

**Comment by ghost** [comment] 2016-07-02 12:29
Disregard seems this issue was fixed in the latest update of extra utilities 2 for 1.10 

Version extrautils2-1.9.4-alpha-1.0.0 fixed the dupe glitch

**Closed as completed** 2016-08-03 18:10 UTC
