### ISSUE TITLE
Extra Utilities Generator Sound Crashes when Switching Dimension

### ISSUE THREAD

**Issue by cproo12** [rwtema/extrautilities_old_issues#208] opened 2014-08-03 05:48 UTC
Whenever I switch a dimension, my game crashes. I have never had the generator sounds work before.

http://pastebin.com/Twd79T28

**Comment by Acters** [comment] 2014-08-03 21:10
same crash: https://github.com/rwtema/extrautilities/issues/205

**Comment by rwtema** [comment] 2014-08-04 12:14
Duplicate of #205

**Closed as completed by rwtema** 2014-08-04 12:14 UTC
