### ISSUE TITLE
Crash client sometimes after second login on server

### ISSUE THREAD

**Issue by simplnic** [rwtema/extrautilities_old_issues#235] opened 2014-08-12 03:53 UTC
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12.08.14 9:42
Description: Ticking screen

java.lang.IllegalArgumentException: value already present: com.rwtema.extrautils.sounds.XUSoundTileGenerators@5684c971
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
    at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:368)
    at net.minecraft.client.audio.SoundHandler.func_147682_a(SourceFile:154)
    at com.rwtema.extrautils.sounds.XUSoundTileGenerators.refresh(XUSoundTileGenerators.java:97)
    at com.rwtema.extrautils.sounds.SoundManager.refresh(SoundManager.java:22)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.onDataPacket(TileEntityGenerator.java:373)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1138)
    at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
    at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
    at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:368)
    at net.minecraft.client.audio.SoundHandler.func_147682_a(SourceFile:154)
    at com.rwtema.extrautils.sounds.XUSoundTileGenerators.refresh(XUSoundTileGenerators.java:97)
    at com.rwtema.extrautils.sounds.SoundManager.refresh(SoundManager.java:22)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.onDataPacket(TileEntityGenerator.java:373)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1138)
    at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
    at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
    Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['all'/5067, l='MpServer', x=809,52, y=66,62, z=1509,01]]
    Chunk stats: MultiplayerChunkCache: 5, 5
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (594,64,813), Chunk: (at 2,4,13 in 37,50; contains blocks 592,0,800 to 607,255,815), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
    Level time: 3828696 game time, 4028113 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 32 total; [EntityBat['Bat'/5070, l='MpServer', x=817,47, y=42,09, z=1517,56], EntitySlime['Slime'/5071, l='MpServer', x=825,13, y=10,00, z=1534,63], EntityItem['item.item.slimeball'/5072, l='MpServer', x=825,25, y=10,00, z=1534,41], EntitySlime['Slime'/5073, l='MpServer', x=810,31, y=20,00, z=1541,31], EntityItem['item.item.slimeball'/5074, l='MpServer', x=784,38, y=10,13, z=1537,53], EntityItem['item.tile.sapling.oak'/5075, l='MpServer', x=833,13, y=62,13, z=1489,88], EntityXPOrb['Experience Orb'/5076, l='MpServer', x=842,84, y=64,59, z=1496,97], EntitySlime['Slime'/5077, l='MpServer', x=782,31, y=11,00, z=1538,69], EntityItem['item.item.string'/5078, l='MpServer', x=773,13, y=20,13, z=1544,25], EntitySheep['Sheep'/5079, l='MpServer', x=753,66, y=74,00, z=1488,56], EntitySpider['Spider'/5080, l='MpServer', x=761,50, y=20,00, z=1539,50], EntityItem['item.item.string'/5081, l='MpServer', x=760,19, y=20,13, z=1539,34], EntitySheep['Sheep'/5082, l='MpServer', x=840,44, y=63,00, z=1456,25], EntitySkeleton['Skeleton'/5083, l='MpServer', x=736,50, y=56,00, z=1510,91], EntityCreeper['Creeper'/5084, l='MpServer', x=740,34, y=56,00, z=1518,66], EntityCreeper['Creeper'/5085, l='MpServer', x=745,50, y=56,00, z=1518,50], EntitySpider['Spider'/5086, l='MpServer', x=738,94, y=55,00, z=1514,06], EntitySheep['Sheep'/5087, l='MpServer', x=803,09, y=67,00, z=1445,47], EntitySheep['Sheep'/5088, l='MpServer', x=867,25, y=63,00, z=1515,44], EntitySheep['Sheep'/5089, l='MpServer', x=876,38, y=63,00, z=1513,69], EntitySheep['Sheep'/5090, l='MpServer', x=746,47, y=75,00, z=1494,66], EntitySheep['Sheep'/5091, l='MpServer', x=751,50, y=68,00, z=1496,34], EntitySheep['Sheep'/5092, l='MpServer', x=823,47, y=62,00, z=1455,38], EntitySheep['Sheep'/5093, l='MpServer', x=825,75, y=63,00, z=1447,66], EntitySheep['Sheep'/5094, l='MpServer', x=816,19, y=69,00, z=1442,50], EntitySheep['Sheep'/5095, l='MpServer', x=876,22, y=64,00, z=1521,28], EntitySheep['Sheep'/5096, l='MpServer', x=749,56, y=69,00, z=1481,34], EntityZombie['Zombie'/5097, l='MpServer', x=842,28, y=30,00, z=1583,59], EntityItem['item.item.string'/5098, l='MpServer', x=761,25, y=23,13, z=1449,72], EntitySheep['Sheep'/5099, l='MpServer', x=884,69, y=64,00, z=1512,50], EntityClientPlayerMP['all'/5067, l='MpServer', x=809,52, y=66,62, z=1509,01], EntityEnderman['Enderman'/5103, l='MpServer', x=735,50, y=55,00, z=1532,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 412446952 bytes (393 MB) / 1004011520 bytes (957 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 1 total; -Xmx2048M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
    FML: MCP v9.05 FML v7.10.25.1199 Minecraft Forge 10.13.0.1199 69 mods loaded, 69 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.25.1199} [Forge Mod Loader](forge-1.7.10-10.13.0.1199.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.0.1199} [Minecraft Forge](forge-1.7.10-10.13.0.1199.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppliedEnergistics2-Core{rv0-stable-10} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{1.0.2.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.0.2.36} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.36-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Core{6.0.17} [BuildCraft](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IC2{2.2.583-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.583-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore{1.7.10R3.0.0B3} [CoFH Core](CoFHCore-[1.7.10]3.0.0B3-26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalFoundation{1.7.10R1.0.0B1} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B1-6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalExpansion{1.7.10R4.0.0B3} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B3-11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    appliedenergistics2{rv0-stable-10} [Applied Energistics 2](appliedenergistics2-rv0-stable-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.958-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.1.0%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Botania{r1.1-100} [Botania](Botania r1.1-100.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Builders{6.0.17} [BC Builders](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Energy{6.0.17} [BC Energy](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Factory{6.0.17} [BC Factory](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Transport{6.0.17} [BC Transport](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Silicon{6.0.17} [BC Silicon](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    chisel{1.5.6} [Chisel](Chisel-1.7.10-1.5.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderStorage{1.4.4.11} [EnderStorage](EnderStorage-1.7.10-1.4.4.11-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.1.0.300} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Baubles{1.0.1.2} [Baubles](Baubles-1.7.10-1.0.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraUtilities{1.1.0f} [Extra Utilities](extrautilities-1.1.0f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.87.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    factorization{1.7.10-0.8.87.1} [Factorization](Factorization-1.7.10-0.8.87.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    factorization.misc{1.7.10-0.8.87.1} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.87.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.1.0.300} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    gravestonemod{1.7.2} [GraveStone](GraveStones-1.7.2_1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GraviSuite{1.7.10-2.0.1} [Graviation Suite](GraviSuite-1.7.10-2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    InfernalMobs{1.5.5} [Infernal Mobs](InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IronChest{6.0.41.729} [Iron Chest](ironchest-1.7.10-6.0.41.729-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Waila{1.5.3} [Waila](Waila-1.5.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Mantle{1.7.10-165.4bc3343} [Mantle](Mantle_mc1.7.10_0.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MapWriter{2.1.2} [MapWriter](MapWriter-1.7.10-2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded{1.7.10R2.8.0RC2} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC2} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC2} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC2} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC2} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC2} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC2} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC2} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC2} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC2} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC2} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC2} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NetherOres{1.7.10R2.3.0RC3} [Nether Ores](NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    harvestcraft{1.7.2d} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedstoneArsenal{1.7.10R1.1.0B3} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Roguelike{1.3.4} [Roguelike Dungeons](roguelike-1.7.10-1.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct{1.6.0d37} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d38.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WailaHarvestability{1.0.4} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    warpbook{${version}} [Warp Book](warpbook-1.2.29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    denseores{1.0} [Dense Ores](DenseOres-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMicroblock{1.1.0.300} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AE2 Version: stable rv0-stable-10 for Forge 10.13.0.1152
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    AE2 Integration: RotaryCraft:OFF, IC2:ON, RC:OFF, BC:ON, MJ5:ON, MJ6:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:ON, Waila:ON, CLApi:OFF, RB:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, FMP:ON
    Launched Version: 1.7.10-Forge10.13.0.1199
    LWJGL: 2.9.1
    OpenGL: GeForce GT 640/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [MAin_Pack.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

<B>And Server message - </B>

[09:42:44] [Netty IO #4/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: ╧ЁюуЁрььр эр тр°хь їюёЄ-ъюья№■ЄхЁх ЁрчюЁтрыр єёЄрэютыхээюх
яюфъы■ўхэшх
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_11]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_11]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_11]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_11]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_11]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDi
rectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870)
~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketCha
nnel.java:208) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEven
tLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_11]
[09:42:44] [Server thread/INFO]: all lost connection: TranslatableComponent{key=
'disconnect.genericReason', args=[Internal Exception: java.io.IOException: ╧ЁюуЁ
рььр эр тр°хь їюёЄ-ъюья№■ЄхЁх ЁрчюЁтрыр єёЄрэютыхээюх яюфъы■ўхэшх], siblings=[],
 style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=nul
l, obfuscated=null, clickEvent=null, hoverEvent=null}}

**Comment by rwtema** [comment] 2014-08-12 05:25
Dupe of #205

**Closed as completed by rwtema** 2014-08-12 05:25 UTC
