### ISSUE TITLE
Crash after Teleporting and Sometimes after joining the server

### ISSUE THREAD

**Issue by Motytheultimate** [rwtema/extrautilities_old_issues#229] opened 2014-08-10 14:46 UTC
[10/8/2014 16:37:25 PM] [Client thread/INFO] [LanteaCraft]: World unloading: 0
[10/8/2014 16:37:25 PM] [Client thread/INFO] [FML]: Applying holder lookups
[10/8/2014 16:37:25 PM] [Client thread/INFO] [FML]: Holder lookups applied
[10/8/2014 16:37:26 PM] [16:37:26] [Client thread/FATAL]: Unreported exception thrown!
[10/8/2014 16:37:26 PM] java.lang.IllegalArgumentException: value already present: com.rwtema.extrautils.sounds.XUSoundTileGenerators@79a5fb98
[10/8/2014 16:37:26 PM]         at com.google.common.collect.HashBiMap.put(HashBiMap.java:238) ~[guava-16.0.jar:?]
[10/8/2014 16:37:26 PM]         at com.google.common.collect.HashBiMap.put(HashBiMap.java:215) ~[guava-16.0.jar:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:368) ~[btj.class:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.client.audio.SoundHandler.func_147682_a(SourceFile:154) ~[btp.class:?]
[10/8/2014 16:37:26 PM]         at com.rwtema.extrautils.sounds.XUSoundTileGenerators.refresh(XUSoundTileGenerators.java:97) ~[XUSoundTileGenerators.class:?]
[10/8/2014 16:37:26 PM]         at com.rwtema.extrautils.sounds.SoundManager.refresh(SoundManager.java:22) ~[SoundManager.class:?]
[10/8/2014 16:37:26 PM]         at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.onDataPacket(TileEntityGenerator.java:373) ~[TileEntityGenerator.class:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1138) ~[bjb.class:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55) ~[gf.class:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10) ~[gf.class:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) ~[bje.class:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591) ~[bao.class:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) ~[bao.class:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[10/8/2014 16:37:26 PM]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_11]
[10/8/2014 16:37:26 PM]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_11]
[10/8/2014 16:37:26 PM]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_11]
[10/8/2014 16:37:26 PM]         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_11]
[10/8/2014 16:37:26 PM]         at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
[10/8/2014 16:37:26 PM]         at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
[10/8/2014 16:37:26 PM] ---- Minecraft Crash Report ----
[10/8/2014 16:37:26 PM] // Why is it breaking :(
[10/8/2014 16:37:26 PM]
[10/8/2014 16:37:26 PM] Time: 8/10/14 4:37 PM
[10/8/2014 16:37:26 PM] Description: Unexpected error
[10/8/2014 16:37:26 PM]
[10/8/2014 16:37:26 PM] java.lang.IllegalArgumentException: value already present: com.rwtema.extrautils.sounds.XUSoundTileGenerators@79a5fb98
[10/8/2014 16:37:26 PM]         at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
[10/8/2014 16:37:26 PM]         at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:368)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.audio.SoundHandler.func_147682_a(SourceFile:154)
[10/8/2014 16:37:26 PM]         at com.rwtema.extrautils.sounds.XUSoundTileGenerators.refresh(XUSoundTileGenerators.java:97)
[10/8/2014 16:37:26 PM]         at com.rwtema.extrautils.sounds.SoundManager.refresh(SoundManager.java:22)
[10/8/2014 16:37:26 PM]         at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.onDataPacket(TileEntityGenerator.java:373)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1138)
[10/8/2014 16:37:26 PM]         at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
[10/8/2014 16:37:26 PM]         at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
[10/8/2014 16:37:26 PM]         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.main.Main.main(SourceFile:148)
[10/8/2014 16:37:26 PM]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10/8/2014 16:37:26 PM]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10/8/2014 16:37:26 PM]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10/8/2014 16:37:26 PM]         at java.lang.reflect.Method.invoke(Unknown Source)
[10/8/2014 16:37:26 PM]         at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
[10/8/2014 16:37:26 PM]         at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10/8/2014 16:37:26 PM]
[10/8/2014 16:37:26 PM]
[10/8/2014 16:37:26 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[10/8/2014 16:37:26 PM] ---------------------------------------------------------------------------------------
[10/8/2014 16:37:26 PM]
[10/8/2014 16:37:26 PM] -- Head --
[10/8/2014 16:37:26 PM] Stacktrace:
[10/8/2014 16:37:26 PM]         at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
[10/8/2014 16:37:26 PM]         at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:368)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.audio.SoundHandler.func_147682_a(SourceFile:154)
[10/8/2014 16:37:26 PM]         at com.rwtema.extrautils.sounds.XUSoundTileGenerators.refresh(XUSoundTileGenerators.java:97)
[10/8/2014 16:37:26 PM]         at com.rwtema.extrautils.sounds.SoundManager.refresh(SoundManager.java:22)
[10/8/2014 16:37:26 PM]         at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.onDataPacket(TileEntityGenerator.java:373)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1138)
[10/8/2014 16:37:26 PM]         at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
[10/8/2014 16:37:26 PM]         at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
[10/8/2014 16:37:26 PM]         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[10/8/2014 16:37:26 PM]         at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
[10/8/2014 16:37:26 PM]
[10/8/2014 16:37:26 PM] -- Affected level --
[10/8/2014 16:37:26 PM] Details:
[10/8/2014 16:37:26 PM]         Level name: MpServer
[10/8/2014 16:37:26 PM]         All players: 1 total; [EntityClientPlayerMP['**MINECRAFTUSERNAME**'/13934, l='MpServer', x=245.50, y=81.62, z=290.50]]
[10/8/2014 16:37:26 PM]         Chunk stats: MultiplayerChunkCache: 89, 89
[10/8/2014 16:37:26 PM]         Level seed: 0
[10/8/2014 16:37:26 PM]         Level generator: ID 00 - default, ver 1. Features enabled: false
[10/8/2014 16:37:26 PM]         Level generator options:
[10/8/2014 16:37:26 PM]         Level spawn location: World: (267,75,214), Chunk: (at 11,4,6 in 16,13; contains blocks 256,0,208 to 271,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[10/8/2014 16:37:26 PM]         Level time: 425884 game time, 453462 day time
[10/8/2014 16:37:26 PM]         Level dimension: 0
[10/8/2014 16:37:26 PM]         Level storage version: 0x00000 - Unknown?
[10/8/2014 16:37:26 PM]         Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
[10/8/2014 16:37:26 PM]         Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

here is the entire log http://paste.atlauncher.com/view/1f9c8922

**Comment by rwtema** [comment] 2014-08-11 08:54
Dupe of #205

**Closed as completed by rwtema** 2014-08-11 08:54 UTC
