### ISSUE TITLE
Crash on login after another crash 

### ISSUE THREAD

**Issue by BeyondAeon** [rwtema/extrautilities_old_issues#234] opened 2014-08-11 22:19 UTC
I'm using lots of mods , so this might not be extrautils but ..... 

I have twice now gotten a crash in another mod, and then upon re-logging i get this crash with your name on it.

java.lang.IllegalArgumentException: value already present: com.rwtema.extrautils.sounds.XUSoundTileGenerators@77767098
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
    at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:368)
    at net.minecraft.client.audio.SoundHandler.func_147682_a(SourceFile:154)
    at com.rwtema.extrautils.sounds.XUSoundTileGenerators.refresh(XUSoundTileGenerators.java:97)
    at com.rwtema.extrautils.sounds.SoundManager.refresh(SoundManager.java:22)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.onDataPacket(TileEntityGenerator.java:373)

( and just crashed again while standing near generators digging a room out )
see here 
http://pastebin.com/hzqYDXdV

**Comment by rwtema** [comment] 2014-08-12 04:44
Dupe of #205

**Closed as completed by rwtema** 2014-08-12 04:44 UTC
