### ISSUE TITLE
Crash with extra utilities

### ISSUE THREAD

**Issue by lenzh** [rwtema/extrautilities_old_issues#486] opened 2015-01-20 13:10 UTC
http://pastebin.com/KHmQ4WLZ

here is the crash report

**Comment by jena-th** [comment] 2015-01-20 13:53
Hello, thank you for the crash report. :) https://gist.github.com/ is a good tool too ! :wink: 

//Yeah, I'm the Gist guy that hang around preaching to use Gist, given the project is on Github… Why not ?

**Comment by lenzh** [comment] 2015-01-20 13:55
@kane-thornwyrd ??

**Comment by jena-th** [comment] 2015-01-20 15:09
@lenzh I am just suggesting that, when we have a Github account we could use Gist instead of pastebin … And gaining some benefits in the process… But that's just a suggestion… I'm still not able to help you with the crash, I'm in learning phase.

**Comment by jena-th** [comment] 2015-01-20 15:10
Anyway, can you describe the faulty contraption, what was the scenario, was it on a well-known modpack ?
Like so we could try to reproduce the bug to fix it.

**Comment by lenzh** [comment] 2015-01-20 16:10
@kane-thornwyrd its a custom modpack that a friend made and he get the error but he dont have Github

**Comment by mentimjojo** [comment] 2015-01-21 11:18
same error indeed.

**Comment by GamingBox** [comment] 2015-01-21 19:15
http://pastebin.com/ZQDKfkQT I had Crash when i opened minecraft

**Comment by lenzh** [comment] 2015-01-21 19:30
@GamingBox what version minecraft do you use

**Comment by jena-th** [comment] 2015-01-22 09:54
Are you three using the same modpack ?

**Comment by jena-th** [comment] 2015-01-22 09:55
Try to launch without Optifine.

**Comment by mentimjojo** [comment] 2015-01-22 11:17
No my own modpack for me and my friends. Version 1.2.0 and 1.2.1 don't work, version 1.1.0k en before works.

**Comment by jena-th** [comment] 2015-01-22 12:36
Maybe you should ask the modpack author to investigate first then.

**Comment by mentimjojo** [comment] 2015-01-22 13:53
@kane-thornwyrd well it is my modpack so i am the author. It is a bug in the mod. Not in my pack.

**Comment by jena-th** [comment] 2015-01-22 14:15
To be exact, there is a conflict between ExtraUtilities v.1.2.x and another mod in your modpack, without any further informations we can't assume that there is "a bug" in ExtraUtilities v.1.2.x, therefore, and since **you** have the full responsibility over **your** modpack, the only decision I would take in this position would be to keep Extra Utilities at version 1.1.0k while investigating the bug to understand which mod conflict and take another decision after.

I'm assembling a modpack, and as a modpacker I think that updating mods and releasing the new modpack version without testing it is a really bad practice, that utterly lack of consideration toward your players.

**Comment by mentimjojo** [comment] 2015-01-23 15:59
@kane-thornwyrd I know that i am not doing that. But the error that i get is not from another mod. I have a error log somewhere so i will post it over here as soon as possible.

**Comment by MrabEzreb** [comment] 2015-01-23 22:20
Ya, I am getting this error too, and apparently nobody can help
Guess im removing EU :'(

**Comment by jena-th** [comment] 2015-01-23 23:36
@rwtema close this issue please, it's a private modpack related problem, those boys don't seem to understand that the responsibility is on them.

**Comment by MrabEzreb** [comment] 2015-01-24 19:49
I would just like to know what mod is causing EU to do this. If @rwtema has any known incompatabilities, I would like to know. I just can't figure out why the stack is overflowing with checking if a certain pipe can output, when I load in an empty world :(

**Comment by jena-th** [comment] 2015-01-24 20:04
When I'm facing the same problem, I try to disable each mod, one by one, until it doesn't crash any more, you'll get the culprit.

**Comment by lenzh** [comment] 2015-01-25 12:50
i still dont have a fix please help me btw this is my issue

**Closed as completed** 2015-01-30 21:40 UTC

**Comment by jena-th** [comment] 2015-02-01 11:48
Did you found the problem ? Or dropped EU ?

**Comment by MrabEzreb** [comment] 2015-02-02 16:11
I dropped it, I really don't understand why it would ever do that. Why in the world would you ever make it a tiny possibility that a stackoverflow could happen! I wouldn't even do public void foo() {if(false == true) {foo()}} !!!!!! What if all logic breaks down and false starts equaling true! Then I would have a stackoverflow error!
