### ISSUE TITLE
Version 1.1.0e Startup Error

### ISSUE THREAD

**Issue by leezallen** [rwtema/extrautilities_old_issues#202] opened 2014-08-01 01:27 UTC
Using version 1.1.0e and MC version 1.7.10 I get the following error message on startup... I am probably missing something stupid but all help greatly appreciated!

---- Minecraft Crash Report ----
// You're mean.

Time: 01/08/14 01:04
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.AbstractMethodError
at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:318)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:279)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AbstractMethodError
at net.minecraft.item.ItemSlab.func_77667_c(SourceFile:37)
at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:522)
at com.rwtema.extrautils.tileentity.enderconstructor.EnderConstructorRecipesHandler.postInit(EnderConstructorRecipesHandler.java:54)
at com.rwtema.extrautils.ExtraUtils.postInit(ExtraUtils.java:1562)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
... 5 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.7.0_55, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1343499584 bytes (1281 MB) / 2049441792 bytes (1954 MB) up to 2049441792 bytes (1954 MB)
JVM Flags: 6 total; -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Xmx2048M -Xms2048M -XX:PermSize=256m -XX:MaxPermSize=512m
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.24.1187 Minecraft Forge 10.13.0.1187 78 mods loaded, 77 mods active
mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
FML{7.10.24.1187} [Forge Mod Loader](craftbukkit.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Forge{10.13.0.1187} [Minecraft Forge](craftbukkit.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
AppliedEnergistics2-Core{rv0-stable-10} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
CodeChickenCore{1.0.2.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
<CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
NotEnoughItems{1.0.2.15} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ChickenShed{1.1.3} [Chicken Shed]([1.7.2] ChickenShed %28v1.1.3%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
bspkrsCore{6.13} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Treecapitator{1.7.2} [Treecapitator]([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
abyssalcraft{1.6.0} [AbyssalCraft](AbyssalCraft-1.7.10-1.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
accore{1.1.0} [AbyssalCraft Core](AbyssalCraft-1.7.10-1.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
CoFHCore{1.7.10R3.0.0B1} [CoFH Core](CoFHCore-[1.7.10]3.0.0B1-19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
EnderIO{2.0_beta} [Ender IO](enderio-2.0_beta.152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ForgeMultipart{1.1.0.297} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.297-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ExtraUtilities{1.1.0e} [Extra Utilities](extrautilities-1.1.0e.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
MetallurgyCore{4.0.3} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Mantle{1.7.10-165.4bc3343} [Mantle](Mantle_mc1.7.10_0.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Natura{2.2.0} [Natura](natura-1.7.10-2.2.0-b1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
BiomesOPlenty{2.0.2} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.943-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Forestry{2.4.2.31} [Forestry for Minecraft](forestry_1.7.10-2.4.2.31.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Railcraft{9.1.0.6} [Railcraft](Railcraft_1.7.10-9.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
GalacticraftCore{3.0.0} [Galacticraft Core](GalacticraftCore-BETA-1.7-3.0.0.136.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Mekanism{7.0.0} [Mekanism](Mekanism-1.7.10-7.0.0.260.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ThermalFoundation{1.7.10R1.0.0B1} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B1-2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ThermalExpansion{1.7.10R4.0.0B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B1-3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
appliedenergistics2{rv0-stable-10} [Applied Energistics 2](appliedenergistics2-rv0-stable-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
asielib{0.2.7} [asielib](AsieLib-1.7.10-0.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Backpack{2.0.0} [Backpack](backpack-2.0.0-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
BiblioCraft{1.7.5} [BiblioCraft](BiblioCraft[v1.7.5][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
BiblioWoodsBoP{1.6} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.6].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
CarpentersBlocks{3.2.5} [Carpenter's Blocks](Carpenter's Blocks v3.2.5 [DEV R3] - MC 1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
customnpcs{1.7.10} [CustomNpcs](CustomNPCs_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
props{1.10} [Decocraft](Decocraft-1.10_1.7.2and1.7.10.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
DragonMounts{r39} [Dragon Mounts](dragonmount_r39_mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
exnihilo{1.34} [Ex Nihilo](Ex-Nihilo-1.34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
GalacticraftMars{3.0.0} [Galacticraft Planets](Galacticraft-Planets-BETA-1.7-3.0.0.136.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft{2.1.0a} [Growthcraft](growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar](growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Apples{2.1.0} [Growthcraft Apples](growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo](growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Bees{2.1.0} [Growthcraft Bees](growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap](growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Grapes{2.1.0} [Growthcraft Grapes](growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Hops{2.1.0} [Growthcraft Hops](growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Rice{2.1.0a} [Growthcraft Rice](growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Waila{1.5.3} [Waila](Waila-1.5.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
MekanismGenerators{7.0.0} [MekanismGenerators](MekanismGenerators-1.7.10-7.0.0.260.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
MekanismTools{7.0.0} [MekanismTools](MekanismTools-1.7.10-7.0.0.260.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Metallurgy{4.0.3} [Metallurgy 4](Metallurgy-1.7.10-4.0.3.36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
redgear_core{2.1.3} [Red Gear Core](RedGearCore-1.7.10-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
redgear_morebackpacks{2.2.1} [More Backpacks](More Backpacks-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Morpheus{1.7.10-1.5.17} [Morpheus](Morpheus-1.7.10-1.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ProjRed|Core{4.4.5.44} [ProjectRed](ProjectRed-Base-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ProjRed|Transmission{4.4.5.44} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.7.10-1.3.2.34-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
OpenComputers{1.3.2.34} [OpenComputers](OpenComputers-MC1.7.10-1.3.2.34-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
parachutemod{1.7.10} [Parachute Mod](parachutemod-1.7.10-2.5.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ProjRed|Transportation{4.4.5.44} [ProjectRed-Transportation](ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ProjRed|Exploration{4.4.5.44} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
TConstruct{1.7.10-1.6.0.jenkins541} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d35.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ProjRed|Compatibility{4.4.5.44} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ProjRed|Integration{4.4.5.44} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ProjRed|Illumination{4.4.5.44} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ProjRed|Expansion{4.4.5.44} [ProjectRed-Expansion](ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
RandomThings{2.1.2} [Random Things](RandomThings-2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
RPGAdvMod{1.0.0} [RPGAdvMod](RPGAdvMod-1.0.0_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
redgear_securecraft{1.2.1} [Securecraft](Securecraft-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
statues{2.1.3} [Statues](statues-1.7.10-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
witchery{0.20.3} [Witchery](witchery-1.7.10-0.20.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
XtraRecipes{3.0} [XtraRecipes](XtraRecipes-3.0_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
McMultipart{1.1.0.297} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.297-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ForgeMicroblock{1.1.0.297} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.297-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
asielibcore{} [AsieLib CoreMod](minecraft.jar) Unloaded->Disabled
Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
AE2 Version: stable rv0-stable-10 for Forge 10.13.0.1152
TConstruct Environment: Environment healthy.
Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, MCPC+, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
AE2 Integration: RotaryCraft:OFF, IC2:OFF, RC:ON, BC:OFF, MJ5:ON, MJ6:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, CLApi:OFF, RB:OFF, FMP:ON
Profiler Position: N/A (disabled)
Player Count: 0 / 20; []
Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
Type: Dedicated Server (map_server.txt)

**Comment by rwtema** [comment] 2014-08-01 01:30
Duplicate of #187

**Closed as completed by rwtema** 2014-08-01 01:30 UTC
