### ISSUE TITLE
Liquid transfer node ceases functionality "randomly"

### ISSUE THREAD

**Issue by tyrope** [rwtema/extrautilities_old_issues#134] opened 2014-06-21 04:14 UTC
Situation 1) I set up a 3x1 N-S infinite water source, with the transfer node facing West on the middle one, inserted 2 World Interaction Upgrades in slot 1, it's not sucking up water.

Situation 2) After some breaking-placing of part of the setup, I got it to suck up water, but it's not transferring it to either of the 2 blocks behind it (via transfer pipes), both being Hydraulicraft machines (Low Pressure Vat, Mixer)

Both of these situations have happened without human interaction, after the setup has run for a while.

(Potential important information: The infinite water source is on the chunk border, the southern most block is on another chunk. As well as the Mixer and the transfer pipe below it.)

Extra Utilities 1.1.0b
Modlist: (excl. extra utilities)

```
Baubles-1.7.2-1.0.0.13.jar
CodeChickenLib-1.7.2-1.1.1.80-universal.jar
appliedenergistics2-rv0-beta-32.jar
BiblioCraft[1.7.1][MC1.7.2].jar
BiomesOPlenty-1.7.2-2.0.0.883-universal.jar
Blood Magic-v1.0.1g.jar
Botania r1.0-57.jar
CodeChickenCore-1.7.2-1.0.0-universal.jar
ExtraCells-2.0.17.jar
fmpintegration-1.2.1.jar
ForgeMultipart-1.7.2-1.1.0.283-universal.jar
HydCraft-1.7.2-2.0.3-8.jar
InventoryTweaks-1.57-116.jar
ironchest-1.7.2-6.0.30.723-universal.jar
Jabba-1.1.4.jar
Mantle-1.7.2-0.2.8.jar
natura-1.7.2-2.2.0a3.jar
NotEnoughItems-1.7.2-1.0.1-universal.jar
PneumaticCraft-1.2.1.jar
Railcraft_1.7.2-9.0.0.0.jar
TConstruct-1.7.2-1.6.0.a14.jar
Thaumcraft-1.7.2-4.1.1.14.jar
ThaumicTinkerer-2.4-147.jar
VeinMiner-1.7.2_0.15.0.jar
Waila-1.5.2a_1.7.2.jar
witchery-1.7.2-0.19.2.jar
```

Using the config from the FTB launcher (1.6.4 configs)

**Comment by rwtema** [comment] 2014-06-28 16:17
Unable to reproduce and I can see no reason for the node to randomly stop working as you describe.

**Comment by tyrope** [comment] 2014-06-28 16:48
I'll upload my save file when I'm at my computer later today, so you can investigate. Thanks for the reply.

**Comment by tyrope** [comment] 2014-06-28 19:27
[Save File](https://www.dropbox.com/s/3ynrpml7n9yz89i/extrautils-liquidnode.rar)
Location: X-464, Y60, Z1229 (Above the staircase to the mines)
Forge version (forgot to list it above) is 1126

**Comment by rwtema** [comment] 2014-07-09 15:11
Should be fixed in next version.

**Closed as completed by rwtema** 2014-07-09 15:11 UTC

**Comment by tyrope** [comment] 2014-07-09 15:37
Thanks for the fix. Deleting the save file from my dropbox to save space.
