### ISSUE TITLE
[1.11.2] Crash when accessing a GUI

### ISSUE THREAD

**Issue by kwpugh** [rwtema/extrautilities_old_issues#1340] opened 2017-02-28 01:55 UTC
Forge: 2252
Crash report: https://gist.github.com/kwpugh/03a37ab521d23af95d50695f0c0d9f5b

Server does not crash, but the client does.

When accessing a GUI from Refined Storage, EU2, Mystic Agriculture the client crashes.  Other GUI from RFTools, and other mods are fine.

**Comment by Hjaldar** [comment] 2017-02-28 08:44
Another dupe of #1320

**Comment by kreezxil** [comment] 2017-03-05 03:59
confirmed on the same forge build 2252, client crashed while looking at creative tabs

dedicated server was unaffected

http://pastebin.com/mdBcYTxN

**Closed as completed** 2017-09-14 17:33 UTC
