### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by D-1337** [rwtema/extrautilities_old_issues#99] opened 2014-05-27 18:54 UTC
I am using the FTB unstable pack I'm mot sure whats causing the problem but it only happens when I try to install extrautilities. Something is conflicting just can't figure it out.
Heres the log before I put extrautilities in:
http://pastebin.com/K1Ff3TeA
And After:
http://pastebin.com/iY7bfAZD
Sorry if this has nothing to do with your mod. 
Thanks for giving the pre-releases.

**Comment by rwtema** [comment] 2014-05-27 19:11
Duplicate of #97 - Try with newer version.

**Closed as completed by rwtema** 2014-05-27 19:11 UTC
Labels: duplicate
