### ISSUE TITLE
Infinite Liquid (yet another negative number bug)

### ISSUE THREAD

**Issue by TherminatorX** [rwtema/extrautilities_old_issues#38] opened 2014-04-23 23:01 UTC
This was reported on the Tinker's Construct wiki. It sounds like this mod is the main culprit, so here is the paste:

"don't know if you guys know, but with thermal explasion and extra utilites you can make a liuid infi glitch.....

what you will need

fuiduct/drum/fluid transposer/casting basen/hopper/chest and RF power
simply transfer the liquids into the drum via a smeltary drain and a fluiduct,

place the drum in the fuild fransposer.... you will see it drop into negative number, leave it a while it will jump to about 2.13 billion, from there output it into a castin basen (yellow) and place a hopper hat link to a chest and BOOM

infi metals (this workds with any liquids)

enjoy"

Sounds pretty cheaty to me, but definitely an issue. I haven't tried it myself yet, but I might soon.

Edit: here is a link to the post-http://tinkers-construct.wikia.com/wiki/Seared_Faucet#comm-9288

**Comment by TherminatorX** [comment] 2014-04-24 01:31
Tested and confirmed. Very odd behavior, but I managed to get it to happen.
![2014-04-23_20 25 54](https://cloud.githubusercontent.com/assets/7256249/2785694/6156bf3a-cb5c-11e3-98b2-242bedab109b.png)
![2014-04-23_20 25 56](https://cloud.githubusercontent.com/assets/7256249/2785695/6159ab5a-cb5c-11e3-986b-c4af70316768.png)
![2014-04-23_20 29 19](https://cloud.githubusercontent.com/assets/7256249/2785696/615c6868-cb5c-11e3-8e32-9d4f9ab3e5af.png)
![2014-04-23_20 29 29](https://cloud.githubusercontent.com/assets/7256249/2785697/615eb320-cb5c-11e3-8b58-2c5be36f6788.png)

**Comment by rwtema** [comment] 2014-04-24 07:38
Duplicate of https://github.com/rwtema/extrautilities/issues/22

**Closed as completed by rwtema** 2014-04-24 07:38 UTC
