### ISSUE TITLE
java.lang.NoClassDefFoundError: com/rwtema/extrautils/tileentity/TileEntityEnderThermicLavaPump

### ISSUE THREAD

**Issue by kosakriszi** [rwtema/extrautilities_old_issues#110] opened 2014-06-03 03:41 UTC
Seems to be a BuildCraft API thing.

Game versions 1.7.2-forge-10.12.1.1079
Buildcraft version 6.0.16
ExtraUtils version 1.1.0a

http://pastebin.com/GDNNyFWf

**Comment by TherminatorX** [comment] 2014-06-03 14:47
This is when you tried to power the pump with BC power?

**Comment by kosakriszi** [comment] 2014-06-03 16:47
Actually, this is when the game launches

**Comment by TherminatorX** [comment] 2014-06-03 17:47
Sorry, I'm still not quite too good with these kind of things, is this a crash, or just an error you noticed?

**Comment by kosakriszi** [comment] 2014-06-03 17:51
This was a crash which was only present on the clientside, the server did not have this problem

**Comment by ghost** [comment] 2014-06-03 17:52
Same Error here, but without Buildcraft installed.

**Comment by rwtema** [comment] 2014-06-03 22:18
I'm guessing something is including the Buildcraft API but not including the proper power classes. This may require some rethinking.

**Comment by rwtema** [comment] 2014-06-03 22:22
Wait you're using buildcraft in this instance? Fuck me I don't know then.

**Comment by kosakriszi** [comment] 2014-06-03 22:29
What version of the BuildCraft API did you build against?

**Comment by TherminatorX** [comment] 2014-06-03 22:53
This seems to be an issue with and without BC, which makes it hard to track down. I haven't dabbled into 1.7 yet, still stuck in the past.

**Comment by Eneitilyn** [comment] 2014-06-04 17:50
I have the exact same issue without buildcraft it crashes on Launch when i install OresPlus-0.6.33_Beta with extrautilities-1.1.0a . Ores Plus has buildcraft api inside( i also tried to be all genious about it and deleted the whole buildcraft named folder and it didn't worked still crashes it) http://pastebin.com/mWmuJESR

**Comment by ghost** [comment] 2014-06-04 19:52
Pre 5a is the latest working for me, newer ones crashes with that error above.

**Comment by Eneitilyn** [comment] 2014-06-05 13:08
confirmed it actually works with pre 5a it's so weird i tried to update ores plus to the most unstable beta alpha (and all other word letter thing versions) but it didn't work and i just downgraded to 5a and it works now

**Comment by kosakriszi** [comment] 2014-06-05 14:54
Hey rwtema, would it be possible for you to build your mod with the Buildcraft 6 API? If it's too much hassle, I understand!

**Comment by Leftorius** [comment] 2014-06-09 12:53
Any update yet? because with that error I can't use extra utilities :/

**Comment by rwtema** [comment] 2014-06-09 21:25
Hopefully fixed in 1.1.0b. I'm now including the new BC API so it shouldn't bring up this particular error anymore.

**Closed as completed by rwtema** 2014-06-09 21:25 UTC
