### ISSUE TITLE
Minecraft 1.12 server crash

### ISSUE THREAD

**Issue by Realever** [rwtema/extrautilities_old_issues#1650] opened 2017-08-14 16:13 UTC
Hi
i have updatet to your new version 1.5.2 but my server crash on startup.My Client doesn´t crash.Here is the crash report: https://pastebin.com/w7xithPg

**Comment by WhiskersWatson** [comment] 2017-08-15 14:01
I am also having this error on just my server and not my client.
https://pastebin.com/htwSqaCu

**Comment by Necavi** [comment] 2017-08-16 03:18
Throwing my hat in here too, I'm having the same issue with Tinker's Construct v2.7.2.19 and Extra Utilities 2 1.5.2.

**Comment by craiven** [comment] 2017-08-16 06:12
if you have crash the world with mechanical crafter. Delete the world files and upload from backup.

**Comment by p-schneider** [comment] 2017-08-17 17:23
This is a duplicate of #1645

**Comment by Realever** [comment] 2017-08-17 17:39
i didn´t see that.i close then my report

**Closed as completed** 2017-08-17 17:39 UTC
